# How many distinct terms are in the sequence generated by a^(b) for 2 <= a  <= 100 and 2 <= b  <= 100?

MIN, MAX = 2,100
values = []

(MIN..MAX).each do |base|
  (MIN..MAX).each do |power|
    values << base**power
  end
end

puts values.uniq.length