#Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:

#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 = 48, is not pentagonal.

#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk  Pj| is minimised; what is the value of D?

def pentagonal n
	(n * (3 * n - 1)) / 2
end

def is_pentagonal? n
	while $pentagonals.last < n
		$pentagonals << pentagonal($pentagonals.count)
	end

	$pentagonals.include? n
end

$pentagonals = [1]

is_pentagonal? 10_000_000

for k in 0..($pentagonals.count - 1) do
	for j in (k + 1)..($pentagonals.count - 1) do
		if is_pentagonal?($pentagonals[j] - $pentagonals[k]) && is_pentagonal?($pentagonals[k] + $pentagonals[j])
			puts $pentagonals[k]
			puts $pentagonals[j]
			exit
		end
	end
end